---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant-test
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: nfs-subdir-external-provisioner
    - name: external-secrets
    - name: authentik
  interval: 30m
  path: ./kubernetes/apps/home-automation/home-assistant-test/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: *namespace
  targetNamespace: home-automation
  timeout: 5m
  wait: false
