---
apiVersion: v1
kind: Service
metadata:
  name: authentik-webfinger
  namespace: identity
  labels:
    app.kubernetes.io/name: authentik-webfinger
    app.kubernetes.io/instance: authentik-webfinger
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: authentik-webfinger
    app.kubernetes.io/instance: authentik-webfinger
