---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: identity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secrets
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flux-system,networking,observability,guacamole"
      data:
        # API token for automation created via the Authentik UI
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL_PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_PASSWORD }}"
        GRAFANA_CLIENT_SECRET: "{{ .GRAFANA_CLIENT_SECRET }}"
        TRAEFIK_CLIENT_SECRET: "{{ .TRAEFIK_CLIENT_SECRET }}"
        WEAVE_GITOPS_CLIENT_SECRET: "{{ .WEAVE_GITOPS_CLIENT_SECRET }}"
        GUACAMOLE_CLIENT_SECRET: "{{ .GUACAMOLE_CLIENT_SECRET }}"
        TAILSCALE_CLIENT_SECRET: "{{ .TAILSCALE_CLIENT_SECRET }}"
        HOMEASSISTANT_TEST_CLIENT_SECRET: "{{ .HOMEASSISTANT_TEST_CLIENT_SECRET }}"
        HOMEASSISTANT_CLIENT_SECRET: "{{ .HOMEASSISTANT_CLIENT_SECRET }}"
        SYNOLOGY_NAS_CLIENT_SECRET: "{{ .SYNOLOGY_NAS_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: authentik-secrets
