---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
