---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          mqtt:
            server: mqtt://{{ .mqtt_host }}:1883
          serial:
            port: tcp://{{ .serial_host }}:6638
          advanced:
            channel: {{ .channel }}
            pan_id: {{ .pan_id }}
            ext_pan_id: [{{ .ext_pan_id }}]
            network_key:
          {{- range $v := splitList "," .network_key }}
              - {{ $v }}
          {{- end }}
  dataFrom:
    - extract:
        key: zigbee2mqtt-network
