---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
patches:
  - path: networkpolicy-patch.yaml
    target:
      kind: NetworkPolicy
      name: flux-operator-web
