---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synology-cert-sync
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager-issuers
    - name: onepassword
  interval: 30m
  path: ./kubernetes/apps/cert-manager/synology-cert-sync/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: *namespace
  targetNamespace: cert-manager
  timeout: 3m
  wait: false
