---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - externalsecret.yaml
  - connector.yaml
labels:
  - pairs:
      app.kubernetes.io/name: tailscale-operator
      app.kubernetes.io/instance: tailscale-operator
