---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
  namespace: &namespace flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: mosquitto
    - name: onepassword
  interval: 30m
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: *namespace
  retryInterval: 1m
  targetNamespace: home-automation
  timeout: 5m
  wait: false
