---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app identity-authentik-saml-setup
  namespace: flux-system
spec:
  targetNamespace: identity
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: identity-authentik
    - name: external-secrets-stores
  path: ./kubernetes/apps/identity/authentik/saml-setup/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
